/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ArosCoin__factory } from "./ArosCoin__factory";
export { ArosCoinReserveManager__factory } from "./ArosCoinReserveManager__factory";
