/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArosCoin } from "./ArosCoin";
export type { ArosCoinReserveManager } from "./ArosCoinReserveManager";
